spring:
  datasource:
    config-local-h2:
      db-path: ./data/mododb
      port: 9394
      mode: 0
    main:
      jdbcUrl: ${APP_DB_URL:jdbc:mysql://10.19.95.33:3306/atlas_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false}
      username: ${APP_DB_USER:prd}
      password: ${APP_DB_PWD:wUl7Y6SFhEmbY5lnPuCobA==}
      driverClassName: ${APP_DB_DRIVER:com.mysql.jdbc.Driver}
      maximumPoolSize: ${APP_DB_POOL_SIZE:2}
      dataSource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
    config:
      jdbcUrl: ${CONF_DB_URL:jdbc:mysql://10.19.95.33:3306/atlas_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false}
      username: ${CONF_DB_USER:prd}
      password: ${CONF_DB_PWD:wUl7Y6SFhEmbY5lnPuCobA==}
      driverClassName: ${CONF_DB_DRIVER:com.mysql.jdbc.Driver}
      maximumPoolSize: ${CONF_DB_POOL_SIZE:2}
      dataSource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
    metadbs:
      jdbcUrl: ${APP_DB_PRO_URL:jdbc:mysql://10.19.95.33:3306/atlas_pro?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false}
      username: ${APP_DB_PRO_USER:prd}
      password: ${APP_DB_PRO_PWD:wUl7Y6SFhEmbY5lnPuCobA==}
      driverClassName: ${METADBS_DB_DRIVER:com.mysql.jdbc.Driver}
      maximumPoolSize: ${METADBS_DB_POOL_SIZE:2}
      dataSource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    database: ${DB_TYPE:mysql}
    database-platform: ${DB_DIALECT:org.hibernate.dialect.MySQL5InnoDBDialect}
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 1GB #限制文件上传大小为1G
      max-request-size: 1GB #限制文件上传大小为1G
  main:
    allow-bean-definition-overriding: true
  groovy:
    template:
      check-template-location: false
  redis:
    # 单点
    host: ${REDIS_HOST:10.19.28.149}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWD:redis123aB}
