from __future__ import annotations

import ast
import json
import re
import importlib
import inspect
from typing import Any, Dict, Iterable, Optional

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from loguru import logger

from core.runtime.executor import execute
from core.runtime.base import OntologyObject
from core.runtime.registry import get_function
import traceback

router = APIRouter(prefix="", tags=["ontology-service"])


class ServiceReq(BaseModel):
    ontology_id: Optional[str] = None
    code: str


def get_objects():
    # TODO: Inject platform objects here
    return None


def _camel_to_snake(name: str) -> str:
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def _iter_ontology_ids() -> Iterable[str]:
    from pathlib import Path
    root = Path("core/ontology")
    if not root.exists():
        return []
    for child in root.iterdir():
        if child.is_dir() and (child / "objects").exists():
            yield child.name


def _get_object_instance(ontology_id: Optional[str], object_name: str) -> Any:
    # module_name = _camel_to_snake(object_name)
    module_name = object_name
    candidates = [ontology_id] if ontology_id else list(_iter_ontology_ids())
    last_error: Optional[Exception] = None
    for oid in candidates:
        try:
            module_path = f"core.ontology.{oid}.objects.{module_name}"
            module = importlib.import_module(module_path)
            if hasattr(module, object_name):
                cls = getattr(module, object_name)
                return cls()
        except Exception as e:
            last_error = e
            continue
    if last_error:
        raise last_error
    raise ImportError(f"Object class '{object_name}' not found in any ontology")


async def _execute_action_direct(ontology_id: Optional[str], object_name: str, method_name: str, params: Dict[str, Any]) -> Any:
    inst = _get_object_instance(ontology_id, object_name)
    if not hasattr(inst, method_name):
        raise AttributeError(f"Method '{method_name}' not found on object '{object_name}'")
    method = getattr(inst, method_name)

    # Fast path for common action_create_obj pattern where generated bound method
    # wrapper exposes (*args, **kwargs). Try passing entire params under 'data'.
    try:
        if isinstance(params, dict):
            reserved = {"pk_value", "pk_values", "where_sql", "where_params", "updates"}
            if not any(k in params for k in reserved):
                if inspect.iscoroutinefunction(method):
                    return await method(data=params)
                return method(data=params)
    except TypeError:
        # Not a data-param action; fall through to normal handling
        pass
    except Exception:
        # Propagate real execution errors
        raise

    # Detect whether the method expects a single 'data' param (create_obj convention)
    try:
        sig = inspect.signature(method)
        # logger.info(f"sig: {sig}, method: {method}")
        # Exclude 'self'
        params_list = [p for p in sig.parameters.values() if p.name != "self"]
        param_names = [p.name for p in params_list]
        # Case 1: single explicit param (commonly named 'data') → pass entire dict as keyword arg
        if len(params_list) == 1 and params_list[0].name != "pk_value":
            logger.info(f"Single param case, params: {params}")
            single_name = params_list[0].name
            if inspect.iscoroutinefunction(method):
                return await method(**{single_name: params})
            return method(**{single_name: params})
        # Case 2: update variant generated by create_obj: signature (pk_value, updates)
        if len(params_list) == 2 and ("pk_value" in param_names and "updates" in param_names):
            # Build updates dict from explicit 'updates' or remaining keys
            reserved_keys = {"pk_value", "pk_values", "where_sql", "where_params", "updates"}
            updates_dict = params.get("updates") if isinstance(params.get("updates"), dict) else {
                k: v for k, v in (params or {}).items() if k not in reserved_keys
            }
            # Single PK takes precedence
            if "pk_value" in params:
                if inspect.iscoroutinefunction(method):
                    return await method(pk_value=params.get("pk_value"), updates=updates_dict)
                return method(pk_value=params.get("pk_value"), updates=updates_dict)
            # Batch update by pk_values
            maps = _collect_ontology_maps(ontology_id)
            if "pk_values" in params:
                pk_values_iter = params.get("pk_values") or []
                return inst.update_many_by_pk(
                    pk_values_iter,
                    updates=updates_dict,
                    ontology_name=ontology_id,
                    object_type_name=object_name,
                    ontology_maps=maps,
                )
            # WHERE-based update
            if params.get("where_sql"):
                return inst.update_many_by_pk(
                    [],
                    updates=updates_dict,
                    ontology_name=ontology_id,
                    object_type_name=object_name,
                    where_sql=params.get("where_sql"),
                    where_params=params.get("where_params"),
                    ontology_maps=maps,
                )
            # Fallback to kwargs
        # Case 3: delete variant generated by create_obj: signature (pk_value)
        if len(params_list) == 1 and params_list[0].name == "pk_value":
            if "pk_value" in params:
                if inspect.iscoroutinefunction(method):
                    return await method(params.get("pk_value"))
                return method(params.get("pk_value"))
            # Batch delete by pk_values
            if "pk_values" in params:
                return inst.delete_many_by_pk(
                    params.get("pk_values") or [],
                    ontology_name=ontology_id,
                    object_type_name=object_name,
                )
            # WHERE-based delete: resolve PKs then delete
            if params.get("where_sql"):
                maps = _collect_ontology_maps(ontology_id)
                pk_attr = getattr(inst, "_primary_key_attr", None)
                if not pk_attr:
                    fmap = getattr(inst, "_field_map", None) or {}
                    if "id" in fmap:
                        pk_attr = "id"
                if not pk_attr:
                    return 0
                pk_values = inst.find(
                    return_attrs=pk_attr,
                    where_sql=params.get("where_sql"),
                    where_params=params.get("where_params"),
                    ontology_maps=maps,
                    ontology_name=ontology_id,
                    object_type_name=object_name,
                )
                try:
                    pk_values_list = list(pk_values or [])
                except Exception:
                    pk_values_list = []
                if not pk_values_list:
                    return 0
                return inst.delete_many_by_pk(
                    pk_values_list,
                    ontology_name=ontology_id,
                    object_type_name=object_name,
                )
    except (ValueError, TypeError) as e:
        # Only catch signature introspection errors, not execution errors
        logger.warning(f"Could not introspect signature for {object_name}.{method_name}: {e}")
        pass
    except Exception:
        # Re-raise any other exceptions (including from method execution)
        raise

    # Default path: kwargs, with fallback for unexpected keyword error
    try:
        if inspect.iscoroutinefunction(method):
            return await method(**params)
        return method(**params)
    except TypeError as te:
        # Fallback: if signature has exactly one non-self param, try passing whole dict as positional
        try:
            sig = inspect.signature(method)
            params_list = [p for p in sig.parameters.values() if p.name != "self"]
            if len(params_list) == 1:
                if inspect.iscoroutinefunction(method):
                    return await method(params)
                return method(params)
        except Exception:
            pass
        raise


def _collect_ontology_maps(ontology_id: Optional[str]) -> Dict[str, Any]:
    """
    Collect object -> table and object.attr -> column mappings for the given ontology.

    Returns a dict with keys:
      - object_to_table: Dict[str, str]
      - object_attr_to_col: Dict[tuple[str, str], str]
      - attr_sets: Dict[str, set[str]]  # object -> set of ontology attrs
    """
    from pathlib import Path
    import importlib

    maps: Dict[str, Any] = {
        "object_to_table": {},
        "object_attr_to_col": {},
        "attr_sets": {},
    }
    if not ontology_id:
        return maps
    obj_dir = Path(f"core/ontology/{ontology_id}/objects")
    if not obj_dir.exists():
        return maps

    for py_file in obj_dir.iterdir():
        if not py_file.is_file() or not py_file.name.endswith(".py"):
            continue
        module_name = py_file.stem
        # Skip __init__ or private modules
        if module_name.startswith("__"):
            continue
        try:
            module_path = f"core.ontology.{ontology_id}.objects.{module_name}"
            module = importlib.import_module(module_path)
        except Exception:
            continue

        # Class name convention: module may equal class, but also support probing attributes
        candidate_class_names = [module_name]
        # Add PascalCase alternative
        if module_name and module_name[:1].islower():
            candidate_class_names.append(module_name[:1].upper() + module_name[1:])

        cls_obj = None
        for cname in candidate_class_names:
            if hasattr(module, cname):
                cls_obj = getattr(module, cname)
                break
        if cls_obj is None:
            # Probe first class defined that has _table_name/_field_map once instantiated
            for name in dir(module):
                obj = getattr(module, name)
                if isinstance(obj, type):
                    cls_obj = obj
                    break
        if cls_obj is None:
            continue
        try:
            inst = cls_obj()
            table = getattr(inst, "_table_name", None)
            field_map = getattr(inst, "_field_map", None) or {}
        except Exception:
            continue
        if not isinstance(table, str) or not isinstance(field_map, dict) or not field_map:
            continue
        obj_name = cls_obj.__name__
        maps["object_to_table"][obj_name] = table
        maps["attr_sets"][obj_name] = set(field_map.keys())
        for attr, col in field_map.items():
            maps["object_attr_to_col"][(obj_name, attr)] = col

    return maps


async def ontology_service_impl(ontology_id: Optional[str], code: str, objects: Any) -> Any:
    text = (code or "").strip()
    # Try patterns: Object.method(args) or BareFunction(args)
    m_obj = re.match(r"^\s*([A-Za-z_][\w]*)\s*\.\s*([A-Za-z_][\w]*)\s*\(\s*(.*)\s*\)\s*$", text, re.DOTALL)
    if m_obj:
        object_name = m_obj.group(1)
        method_name = m_obj.group(2)
        args_str = m_obj.group(3)
    else:
        m_func = re.match(r"^\s*([A-Za-z_][\w]*)\s*\(\s*(.*)\s*\)\s*$", text, re.DOTALL)
        if not m_func:
            raise ValueError("Unsupported code format. Expect 'Object.method({...})' or 'Function({...})'.")
        object_name = ""
        method_name = m_func.group(1)
        args_str = m_func.group(2)

    # Parse args as JSON first, fallback to Python literal
    params_dict: Dict[str, Any] = {}
    if args_str:
        try:
            params_dict = json.loads(args_str)
        except Exception:
            try:
                literal = ast.literal_eval(args_str)
                if isinstance(literal, dict):
                    params_dict = literal
                else:
                    params_dict = {"value": literal}
            except Exception:
                params_dict = {}
    # Dispatch
    if not object_name and method_name.lower() == "check_attr_mapping":
        # 支持单对象与批量两种方式：
        # - Object.check_attr_mapping() -> 单对象映射
        # - Object.check_attr_mapping({"objects": ["A","B"]}) -> 批量映射
        obj_list = params_dict.get("objects") or params_dict.get("object_names")
        if obj_list:
            maps = _collect_ontology_maps(ontology_id)
            base = OntologyObject()
            return base.check_attr_mapping(object_names=list(obj_list or []), ontology_name=ontology_id, ontology_maps=maps)
        inst = _get_object_instance(ontology_id, object_name)
        return inst.check_attr_mapping()
    if object_name and method_name.lower() == "find":
        where_sql = params_dict.get("where_sql")
        inst = _get_object_instance(ontology_id, object_name)
        # Let base.find handle mapping of where_sql/order_by/return_attrs
        order_by = params_dict.get("order_by") or params_dict.get("order_by_column")
        ontology_maps = _collect_ontology_maps(ontology_id)
        if where_sql:
            res = inst.find(
                return_attrs=params_dict.get("return_attrs"),
                where_sql=where_sql,
                where_params=params_dict.get("where_params"),
                order_by=order_by,
                page_size=params_dict.get("page_size"),
                page_token=params_dict.get("page_token"),
                ontology_maps=ontology_maps,
                ontology_name=ontology_id,
                object_type_name=object_name,
                save_long_data=True,
            )
        else:
            page_size = params_dict.get("page_size")
            page_token = params_dict.get("page_token")
            order_by = order_by
            if page_size is not None or page_token is not None or order_by is not None:
                res = inst.find(
                    return_attrs=params_dict.get("return_attrs"),
                    where_sql="1=1",
                    where_params=None,
                    order_by=order_by,
                    page_size=page_size,
                    page_token=page_token,
                    ontology_maps=ontology_maps,
                    ontology_name=ontology_id,
                    object_type_name=object_name,
                    save_long_data=True,
                )
            else:
                cond = params_dict.get("condition") or {}
                res = inst.find(
                    return_attrs=params_dict.get("return_attrs"),
                    ontology_maps=ontology_maps,
                    ontology_name=ontology_id,
                    object_type_name=object_name,
                    save_long_data=True,
                    **cond,
                )
        return res

    # Global complex_sql(sql, ...) support: no object required
    if not object_name and method_name.lower() == "complex_sql":
        params_dict = params_dict or {}
        sql_text = params_dict.get("sql")
        if not isinstance(sql_text, str) or not sql_text.strip():
            raise ValueError("complex_sql requires a non-empty 'sql' string parameter")
        maps = _collect_ontology_maps(ontology_id)
        inst = OntologyObject()
        res = inst.complex_sql(
            sql=sql_text,
            ontology_name=ontology_id,
            params=params_dict.get("params"),
            page_size=params_dict.get("page_size"),
            page_token=params_dict.get("page_token"),
            need_total_count=params_dict.get("need_total_count", True),
            ontology_maps=maps,
            save_long_data=True,
        )
        return res
    # Global check_attr_mapping support: no object required
    if not object_name and method_name.lower() == "check_attr_mapping":
        params_dict = params_dict or {}
        obj_list = params_dict.get("objects") or params_dict.get("object_names") or []
        maps = _collect_ontology_maps(ontology_id)
        inst = OntologyObject()
        return inst.check_attr_mapping(object_names=list(obj_list or []), ontology_name=ontology_id, ontology_maps=maps)

    # Support complex_query routing
    if object_name and method_name.lower() in ("complex_query", "complexquery"):
        inst = _get_object_instance(ontology_id, object_name)
        ontology_maps = _collect_ontology_maps(ontology_id)
        res = inst.complex_query(
            select=params_dict.get("select") or [],
            where_sql=params_dict.get("where_sql"),
            joins_sql=params_dict.get("joins_sql"),
            group_by=params_dict.get("group_by"),
            having=params_dict.get("having"),
            order_by=params_dict.get("order_by") or params_dict.get("order_by_column"),
            page_size=params_dict.get("page_size"),
            page_token=params_dict.get("page_token"),
            ontology_maps=ontology_maps,
            ontology_name=ontology_id,
            object_type_name=object_name,
        )
        return res

    # Support aggregate routing (also accept common typo 'aggreate')
    if object_name and method_name.lower() == "aggregate":
        inst = _get_object_instance(ontology_id, object_name)
        ontology_maps = _collect_ontology_maps(ontology_id)
        res = inst.aggregate(
            aggregations=params_dict.get("aggregations") or [],
            where_sql=params_dict.get("where_sql"),
            joins_sql=params_dict.get("joins_sql"),
            group_by=params_dict.get("group_by"),
            having=params_dict.get("having"),
            order_by=params_dict.get("order_by") or params_dict.get("order_by_column"),
            page_size=params_dict.get("page_size"),
            page_token=params_dict.get("page_token"),
            ontology_maps=ontology_maps,
            ontology_name=ontology_id,
            object_type_name=object_name,
        )
        return res

    if object_name:
        try:
            return await _execute_action_direct(ontology_id, object_name, method_name, params_dict)
        except Exception as action_err:
            logger.info(f"action执行失败，尝试函数执行: {action_err}")
            # fall back to any ontology function
            # if ontology_id:
            #     return await execute(ontology_id, method_name, params_dict, objects)
            # # try across all ontologies by probing registry
            # for oid in _iter_ontology_ids():
            #     if get_function(oid, method_name):
            #         return await execute(oid, method_name, params_dict, objects)
            raise ValueError(f"Action '{method_name}' execution failed: {action_err}")

    # Bare global function (allow aliasing of function names via registry)
    # Bare global function
    try:
        if ontology_id:
            return await execute(ontology_id, method_name, params_dict, objects)
        for oid in _iter_ontology_ids():
            if get_function(oid, method_name):
                return await execute(oid, method_name, params_dict, objects)
    except Exception as e:
        logger.info(f"函数执行失败: {e}")
        logger.info(f"{traceback.format_exc()}")
        raise ValueError(f"Function '{method_name}' execution failed: {e}, double check the method you are calling is 'action' or 'function', action needs to be called with 'object'.'action'({{...}})")
    raise ValueError(f"Function '{method_name}' not found in any ontology")


@router.post("/ontology_service")
async def ontology_service(body: ServiceReq, objects=Depends(get_objects)) -> Any:
    logger.info(f"ontology_service 执行: {body.code}")
    try:
        res = await ontology_service_impl(body.ontology_id, body.code, objects)
        return res
    except Exception as e:
        logger.error(f"ontology_service 执行异常: {e}")
        return {"status": "error", "message": str(e)}


