import React from 'react';

import {
	IconLayoutColumn,
	IconTab,
	IconTable,
	IconLineChart,
	IconTask,
	IconRadio,
	IconChexkbox,
	IconDropdown,
	IconWindow,
	IconText,
	IconImage,
	IconCoercion,
	IconLineChartFill,
	IconPieChartFill,
	IconBarChartFill,
	IconWordRecognition,
	IconDataRedundancy,
	IconCalendar,
	IconNodeTree,
	IconCheckboxDropdown,
	IconSwapRight,
	IconStarFill,
	IconInformation
} from 'modo-design/icon';

export default {
	'flexLayout': <IconLayoutColumn />,
	'container': <IconLayoutColumn />,
	'gridLayout': <IconLayoutColumn />,
	'resizeBox': <IconLayoutColumn />,
	'iframe': <IconLayoutColumn />,
	'tabs': <IconTab />,
	'table': <IconTable />,
	'graph': <IconLineChart />,
	'form': <IconTask />,
	'input': <IconText />,
	'inputNumber': <IconText />,
	'inputTag': <IconText />,
	'autoComplete' : <IconText />,
	'textarea': <IconText />,
	'radioGroup': <IconRadio />,
	'checkboxGroup': <IconChexkbox />, 
	'select': <IconDropdown />,
	'slider': <IconDropdown />,
	'button': <IconWindow />,
	'buttonGroup': <IconWindow />,
	'dropdown': <IconDropdown />,
	'cron': <IconDropdown />,
	'text': <IconText />,
	'tag': <IconText />,
	'face': <IconText />,
	'image': <IconImage />,
	'icon': <IconCoercion />,
	'progress': <IconRadio />,
	'steps': <IconRadio />,
	'line': <IconLineChartFill/>,
	'column': <IconBarChartFill />,
	'pie': <IconPieChartFill />,
	'pieDonut': <IconPieChartFill />,
	'radar': <IconDataRedundancy />,
	'wordCloud': <IconWordRecognition />,
	'datePicker': <IconCalendar />,
	'rangePicker': <IconCalendar />,
	'tree': <IconNodeTree />,
	'treeSelect': <IconCheckboxDropdown />,
	'cascader': <IconNodeTree />,
	'upload': <IconDropdown />,
	'switch': <IconSwapRight />,
	'editor': <IconSwapRight />,
	'tableForm': <IconSwapRight />,
	'rate': <IconStarFill />,
	'alert': <IconInformation />,
	'carousel': <IconInformation />,
	'transfer': <IconStarFill />,
	'divider': <IconStarFill />,
	'treeChart': <IconNodeTree />,
	'formList': <IconNodeTree />,
	'cascaderPanel': <IconNodeTree />,
	'tabsForm': <IconNodeTree />,
	'formGroup': <IconNodeTree />
}