spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    config-local-h2:
      mode: -1
      db-path: /
    main:
      jdbcUrl: ${APP_DB_URL:jdbc:mysql://10.1.251.221:5506/dmg_copilot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false}
      username: ${APP_DB_USER:modo}
      password: ${APP_DB_PWD:rlkQ2rQ==}
      driverClassName: ${APP_DB_DRIVER:com.mysql.jdbc.Driver}
      maximumPoolSize: ${APP_DB_POOL_SIZE:20}
      connectionTimeout: ${APP_DB_CONNECTION_TIMEOUT:30000}
      dataSource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
    metadbs:
      jdbcUrl: ${APP_DB_PRO_URL:jdbc:mysql://10.1.251.221:5506/dataos_pro?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false}
      username: ${APP_DB_USER:modo}
      password: ${APP_DB_PWD:rlkQxCunT2rQ==}
      driverClassName: ${APP_DB_DRIVER:com.mysql.jdbc.Driver}
      maximumPoolSize: ${APP_DB_POOL_SIZE:20}
      connectionTimeout: ${APP_DB_CONNECTION_TIMEOUT:30000}
      dataSource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
    config:
      import: dataflow.yaml
      jdbcUrl: ${spring.datasource.main.jdbcUrl}
      username: ${spring.datasource.main.username}
      password: ${spring.datasource.main.password}
      driverClassName: ${spring.datasource.main.driverClassName}
      maximumPoolSize: 2
      dataSource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  main:
    allow-bean-definition-overriding: true
  jpa:
    database: ${DB_TYPE:mysql}
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQL5InnoDBDialect}
        generateDdl: false

  redis:
# 单点
    host: ${REDIS_HOST:10.19.28.149}
    port: ${REDIS_PORT:6379}
# 哨兵
#    sentinel:
#      master: ${REDIS_SENTINEL_MASTER:mymaster}
#      nodes: ${REDIS_INFO:host1:port1,host2:port2,host3:port3}
    password: ${REDIS_PASSWD:redispassword}

suanchou:
  microservice:
    admin:
      host: ${APISIX_ADMIN_HOST:http://10.19.28.149:80}
    gateway:
      host: ${APISIX_GATEWAY_HOST:http://10.19.28.149:80}
      app-secret: ${APISIX_SECRET:ch1vxh4leq}
      upstream-nodes-expr: $.node.value.upstream.nodes
      connTimeout: ${APISIX_CONN_TIMEOUT:10}
      sendTimeout: ${APISIX_SEND_TIMEOUT:6000}
      readTimeout: ${APISIX_READ_TIMEOUT:6000}

# flowable参数，默认关闭
# flowable:
  # async-executor-activate: false
  # database-schema-update: true
  # idm:
    # enabled: false
  # cmmn:
    # enabled: false
  # dmn:
    # enabled: false
  # app:
    # enabled: false

aap:
  host: 10.19.93.128
  port: 30015

sandbox:
  dev:
    host: ${SANDBOX_HOST:10.21.20.170}
    dest-port: ${SANDBOX_DEST_PORT:8031} #vscode
    port: ${SANDBOX_PORT:8032}
  pro:
    host: ${SANDBOX_HOST:10.21.20.170}
    dest-port: ${SANDBOX_DEST_PORT_PRO:8033}
    port: ${SANDBOX_PORT_PRO:8034}
